/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SensorCollection = Collection & {
  member?: ({
    "@id": string;
    [k: string]: any;
  } & {
    "@type"?: string | any[];
    [k: string]: any;
  })[];
  [k: string]: any;
};
export type Collection = Pagination & {
  member?: {
    "@id": string;
    [k: string]: any;
  }[];
  [k: string]: any;
};

export interface Pagination {
  meta?: {
    prev?: {
      "@type"?: string;
      offset?: number;
      limit?: number;
      [k: string]: any;
    };
    current: {
      "@type"?: string;
      offset?: number;
      limit?: number;
      [k: string]: any;
    };
    next?: {
      "@type"?: string;
      offset?: number;
      limit?: number;
      [k: string]: any;
    };
    [k: string]: any;
  };
  [k: string]: any;
}
